### ISSUE TITLE
Default location for config file?

### ISSUE THREAD

**Issue by CarsonF** [paperhive/ansible-ec2-inventory#2]
Would be great to not have to pass in the config file everytime.
Could it default to `/etc/ansible/ec2.ini` or maybe CWD?

**Comment by andrenarchy** [comment]
Good idea! `/etc/ansible/ec2.ini` sounds reasonable because it's the recommendation in the ansible docs. I'll prepare a PR.

**Comment by andrenarchy** [comment]
I uploaded the new release (0.1.6) to PyPi.
